name: Test for workspace

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Xcodebuild resolve
        run: xcodebuild -resolvePackageDependencies -workspace Example.xcworkspace -scheme Example
        working-directory: ./Example
