name: Test 1 (resolve & test)

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Xcodebuild resolve
        run: xcodebuild -resolvePackageDependencies
        working-directory: ./Example

      - name: Xcodebuild test
        run: xcodebuild -scheme Example -destination 'platform=iOS Simulator,name=iPhone 15' test
        working-directory: ./Example
