name: Test 1 (resolve & test)

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Xcodebuild resolve
        run: xcodebuild -resolvePackageDependencies
        working-directory: ./Example

      - name: Xcodebuild test
        run: xcodebuild -scheme Example -destination 'platform=iOS Simulator,name=iPhone 12' test
        working-directory: ./Example
